name: Update JS dependencies

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'package.json'

jobs:
  update:
    name: Install and update JS dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: npm install --no-package-lock
      - name: Commit and push changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Update js dependencies" || exit 0
          git push
